name: dart_common_extensions
description: "Dart extensions for common use cases."
version: 0.0.2
homepage: https://github.com/ceeyang/dart_extensions

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  decimal: ^2.3.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

target:
  flutter:
    platforms:
      - android
      - ios
      - linux
      - macos
      - web
      - windows

flutter:
