name: dart_common_extensions
description: "Dart extensions for common use cases."
version: 0.0.2
homepage: https://github.com/ceeyang/dart_extensions

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl: ^0.18.0
  decimal: ^2.3.0

dev_dependencies:
  test: ^1.24.0
  lints: ^2.1.0

target:
  flutter:
    platforms:
      - android
      - ios
      - linux
      - macos
      - web
      - windows

flutter:
