name: dart_common_extensions
description: "This package provides a collection of convenient extensions for Dart `DateTime`, `List`, `Map`, and `String` classes, aimed at simplifying common operations and enhancing code readability."
version: 0.0.3
homepage: https://github.com/ceeyang/dart_extensions
license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl: ^0.20.0
  decimal: ^3.1.0

dev_dependencies:
  test: ^1.24.0
  lints: ^2.1.0

target:
  flutter:
    platforms:
      - android
      - ios
      - linux
      - macos
      - web
      - windows

flutter:

repository: https://github.com/ceeyang/dart_extensions
documentation: https://pub.dev/documentation/dart_common_extensions/latest/
example: example/dart_common_extensions_example.dart
